- hosts: all
  vars:
    root_dir: /var/www/html
    nginx_port: 80

  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
      become: true

    - name: update nginx config
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
      become: true

    - name: update index.html
      ansible.builtin.template:
        src: ./files/index.html
        dest: "{{ root_dir }}/index.html"
      become: true
      tags: copy_files
        
  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: true
